version: "3"

services:

  gdlint:
    build:
      context: dockerfiles
      dockerfile: gdtoolkit.Dockerfile
    volumes:
      - .:/workdir
    command: gdlint addons/local-backup

  gdformat:
    build:
      context: dockerfiles
      dockerfile: gdtoolkit.Dockerfile
    volumes:
      - .:/workdir
    command: gdformat addons/local-backup
